### ISSUE TITLE
 How can I figure out which status codes are available in onR5StreamStatus method?

### ISSUE THREAD

**Issue by konstantin-tcherkashin** [red5pro/red5pro-ios-app#79]
I need a list of available status codes and I can't find it. Please help

**Comment by beetlejesss** [comment]
Our iOS API documentation can be found here: https://www.red5pro.com/docs/static/ios-streaming/  
Hopefully this helps!

**Comment by konstantin-tcherkashin** [comment]
I've searched in docs, but I can't find status codes list. Can you show me where they are?

**Comment by beetlejesss** [comment]
hm. maybe missing from the docs. Here's the list though:
enum r5_status{
       r5_status_connected,
       r5_status_disconnected,
       r5_status_connection_error,
       r5_status_connection_timeout,
       r5_status_connection_close,
       r5_status_start_streaming,
       r5_status_stop_streaming,
       r5_status_netstatus
   };

**Comment by beetlejesss** [comment]
note - the status codes can be found in the API doc as of our 1.3.0 release (see https://www.red5pro.com/docs/static/ios-streaming/protocol_r5_stream_delegate-p.html)
