### ISSUE TITLE
[R5 ERROR] Invalid signature on publish or subscribe

### ISSUE THREAD

**Issue by tuncertirnavali** [red5pro/red5pro-ios-app#84]
I'm getting following error logs from Xcode while trying to broadcast or subscribe. I can broadcast and subscribe on the AWS server via browser. How can i fix it?

[R5 INFO] connect_client on X.X.X.X:5080/live/test_stream
[R5 DEBUG]Starting audio graph
[R5 ERROR] Invalid signature
[R5 INFO] Calling shutdown
[R5 DEBUG]Closed the socket
[R5 DEBUG]Closing stats timer...
[R5 DEBUG]Closing video mixer...
[R5 DEBUG]Closing main time...
[R5 DEBUG]Closing async handle
[R5 DEBUG]Released client contents

**Comment by beetlejesss** [comment]
The Red5 Pro mobile SDK can only be used with Red5 Pro server. That error would show if you were using Red5 open source or other streaming server.

**Comment by tuncertirnavali** [comment]
There is actually a Red5 Pro Server(Version  1.3.1.b116-release).

**Comment by beetlejesss** [comment]
If you're using this test app, you should leave the default RTSP port (8554) for mobile broadcast/subscribe.  Make sure that port is also open on the server.

**Comment by kashifmin** [comment]
Having same issues on the example Android app:

12-25 21:07:06.616 30614-30834/com.kashifminhaj.red5starter I/r5pro: Starting R5Pro Client Version 1.3.0.0
12-25 21:07:06.616 30614-30834/com.kashifminhaj.red5starter I/r5pro: >>start_client
12-25 21:07:06.616 30614-30834/com.kashifminhaj.red5starter I/r5pro: connect_client on 192.168.43.219:5080/live/red5prostream
12-25 21:07:06.840 30614-30834/com.kashifminhaj.red5starter I/System.out: Stream Listener - Connected
12-25 21:07:06.845 30614-30834/com.kashifminhaj.red5starter I/r5pro: Invalid signature
12-25 21:07:06.846 30614-30834/com.kashifminhaj.red5starter I/System.out: Stream Listener - Disconnected
12-25 21:07:06.846 30614-30834/com.kashifminhaj.red5starter I/System.out: Disconnected
12-25 21:07:06.846 30614-30834/com.kashifminhaj.red5starter I/r5pro: Calling shutdown


I'm using red5pro-server-1.3.1.b116-release

**Comment by beetlejesss** [comment]
Please try downloading the latest version of the server (2.0.0) https://account.red5pro.com/download/red5.
